// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

const TableNameEmbedding = "embedding"

// Embedding mapped from table <embedding>
type Embedding struct {
	ID      uint64 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"` // 編號
	Title   string `gorm:"column:title;type:varchar(255);not null" json:"title"`
	Heading string `gorm:"column:heading;type:varchar(255);not null" json:"heading"`
	Vectors string `gorm:"column:vectors;type:text;not null" json:"vectors"`
	Content string `gorm:"column:content;type:text;not null" json:"content"`
}

// TableName Embedding's table name
func (*Embedding) TableName() string {
	return TableNameEmbedding
}
